# Generated by Django 4.2.4 on 2023-08-11 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=20)),
                ('Token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='user_id',
            new_name='account_balance',
        ),
        migrations.AddField(
            model_name='mobile',
            name='account_sid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='mobile',
            name='account_type',
            field=models.CharField(default='Trial', max_length=10),
        ),
        migrations.AddField(
            model_name='mobile',
            name='user_name',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
