# Generated by Django 4.2.4 on 2023-08-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_token_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
