# Generated by Django 4.2.4 on 2023-08-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_mobile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='account_balance',
            field=models.IntegerField(default=100),
        ),
    ]
