# Generated by Django 4.2.4 on 2023-08-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_mobile_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
