# Generated by Django 4.2.4 on 2023-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_mobile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='token',
        ),
        migrations.AlterField(
            model_name='token',
            name='Token',
            field=models.UUIDField(editable=False),
        ),
    ]
