# Generated by Django 4.2.4 on 2023-10-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_transactions_token_alter_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='sni',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
